### ISSUE TITLE
Key override issue

### ISSUE THREAD

**Issue by yovanoc** [MadeInPierre/finalynx#41]
Il serait bien de séparer les key par supports. car j’ai un CTO et un PEA sur Boursorama par exemple et je ne peut pas changer le nom des champs « liquidités » du coup dans le code actuel il y en a qu’un seul qui ressort car ca doit écraser l’autre

**Comment by MadeInPierre** [comment]
Je regarde ça, je vais peut-être lier la solution avec #39 en fonction de de que je trouve :+1:

**Comment by MadeInPierre** [comment]
I just added support to use a unique ID defined in the Finary API instead of the investment name:

![image](https://user-images.githubusercontent.com/12670280/227058284-faad0b77-5cc2-4cd8-8649-e728d4736240.png)

Now, you can either specify the investment name or id in the `key` field when defining your portfolio:

![image](https://user-images.githubusercontent.com/12670280/227058639-f24077e4-ee7a-421f-9557-f89bba07fcbb.png)

Let me know if that solution answers your issue! You can reopen this issue if needed or ask how to get this new version.

**Comment by MadeInPierre** [comment]
Added a note message in the [documentation here](https://finalynx.readthedocs.io/en/latest/tutorials/getting_started.html#define-your-portfolio) for usage.
