### ISSUE TITLE
Crypto Missing

### ISSUE THREAD

**Issue by yovanoc** [MadeInPierre/finalynx#42]
Il n'y a pas du tout la partie crypto dans les keys proposées, est-ce normal ?

**Comment by yovanoc** [comment]
Ok, I never done python coding but can try. How can we launch the examples/demo script to use the current state of the code? when I try to launch it that way it gives me this:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/7302317/227053617-9e67632d-c98e-4c75-b380-d2e43fdc9008.png">

and that's what I tried

<img width="365" alt="image" src="https://user-images.githubusercontent.com/7302317/227053675-c83b9796-92a4-4537-9c5e-8706883a2299.png">

**Comment by MadeInPierre** [comment]
Weird, the project should be stable. The [latest version](https://github.com/MadeInPierre/finalynx/blob/8ef103a013d5a06f2e896b50612482f0d450de79/examples/demo.py#LL13-L16C31) uses global imports (without dots, meaning finalynx must be installed globally in order to work properly):

![image](https://user-images.githubusercontent.com/12670280/227055483-eb7ac4ca-3dc6-400d-ac50-7fe581d186e2.png)

Some ideas:
- Is the repo up to date? Maybe do a git pull just in case?
- Are you using Python version 3.8 or later?
- Have you installed the project in editable mode? Use `pip install -e .` at the root of the repo, which is equivalent to `pip install finalynx` but it using the local repo.
- Have you installed all dependencies using `poetry install`?

You should be able to simply run the demo without any code change:
```
python examples/demo.py
```

Let me know if that helps! Maybe the [initial setup tutorial](https://finalynx.readthedocs.io/en/latest/project/contributing.html#initial-setup) could be useful too. Let's try to setup your local project first, and then I'll try to give you my best advice on where to start to add cryptos. If the setup tutorial isn't clear enough, I'd be happy to explain it further (Python is awesome but it can be confusing sometimes ^^)

**Comment by yovanoc** [comment]
Ok mb I didn't know the `pip install -e .` to install it from the project and allow me to modify it and test.

I've started the crypto part and I think I will open a PR today. thanks

**Comment by MadeInPierre** [comment]
Great!

I'll take a look in a moment, ideally you shouldn't need to modify finary_api but I've never tried using cryptos. Be right back!

**Comment by yovanoc** [comment]
Yeah already updated it. Don't worry for git things I'm a pro' developer, just never coded in Python 😂

**Comment by MadeInPierre** [comment]
Got it sorry x) You'll teach me one day then :stuck_out_tongue: 

Several options:
1. Make a PR in finary_api with what you suggested, looks like the author forgot it or isn't using it in command-line (`__main__.py` is called when you do `python -m mypackage`).
2. Specify the location of the method by using:
```python
ff.user_portfolio.get_portfolio_cryptos(session)
```
3. Looks like this method only has one line, simply use the shortcut directly (`get_portfolio` is available in `__main__`):
```python
ff.get_portfolio(session, "cryptos")
```

**Comment by yovanoc** [comment]
> Got it sorry x) You'll teach me one day then 😛

What do you mean? I didn't want to be rude saying that.

Otherwise,  thank you option 2 is good !

**Comment by MadeInPierre** [comment]
Sure no worries! I simply meant I'd be happy to learn from you since this is literally my first public repo, there's surely plenty of stuff to improve here and I'd love to know about it ^^
